import type { FormPlugin } from '@/plugins'
import { generateUUID } from '@/utils/uuid'

export const builtinPlugin: FormPlugin = {
  name: 'builtin',
  components: [
    {
      type: 'input',
      name: '单行输入',
      icon: 'EditOutlined',
      category: 'basic',
      component: () => import('@/components/form/Input.vue'),
      defaultConfig: { title: '单行输入', placeholder: '请输入' },
      meta: { hasPlaceholder: true },
    },
    {
      type: 'textarea',
      name: '多行文本',
      icon: 'FormOutlined',
      category: 'basic',
      component: () => import('@/components/form/Textarea.vue'),
      defaultConfig: { title: '多行文本', placeholder: '请输入' },
      meta: { hasPlaceholder: true },
    },
    {
      type: 'number',
      name: '数字输入',
      icon: 'NumberOutlined',
      category: 'basic',
      component: () => import('@/components/form/Number.vue'),
      defaultConfig: { title: '数字输入', placeholder: '请输入数字' },
      meta: { hasPlaceholder: true },
    },
    {
      type: 'switch',
      name: '开关',
      icon: 'SwapOutlined',
      category: 'basic',
      component: () => import('@/components/form/Switch.vue'),
      defaultConfig: { title: '开关', defaultValue: false },
    },
    {
      type: 'rate',
      name: '星级评分',
      icon: 'StarOutlined',
      category: 'basic',
      component: () => import('@/components/form/Rate.vue'),
      defaultConfig: { title: '星级评分', defaultValue: 0 },
    },
    {
      type: 'slider',
      name: '滑块',
      icon: 'ControlOutlined',
      category: 'basic',
      component: () => import('@/components/form/Slider.vue'),
      defaultConfig: { title: '滑块', defaultValue: 0, props: { min: 0, max: 100, step: 1 } },
    },
    {
      type: 'radio',
      name: '单项选择',
      icon: 'CheckCircleOutlined',
      category: 'choice',
      component: () => import('@/components/form/Radio.vue'),
      defaultConfig: {
        title: '单项选择',
        options: [
          { id: generateUUID(), label: '选项1', value: '1' },
          { id: generateUUID(), label: '选项2', value: '2' },
          { id: generateUUID(), label: '选项3', value: '3' },
        ],
      },
      meta: { hasOptions: true },
    },
    {
      type: 'checkbox',
      name: '多项选择',
      icon: 'CheckSquareOutlined',
      category: 'choice',
      component: () => import('@/components/form/Checkbox.vue'),
      defaultConfig: {
        title: '多项选择',
        options: [
          { id: generateUUID(), label: '选项1', value: '1' },
          { id: generateUUID(), label: '选项2', value: '2' },
          { id: generateUUID(), label: '选项3', value: '3' },
        ],
      },
      meta: { hasOptions: true },
    },
    {
      type: 'select',
      name: '下拉选择',
      icon: 'DownOutlined',
      category: 'choice',
      component: () => import('@/components/form/Select.vue'),
      defaultConfig: {
        title: '下拉选择',
        placeholder: '请选择',
        options: [
          { id: generateUUID(), label: '选项1', value: '1' },
          { id: generateUUID(), label: '选项2', value: '2' },
          { id: generateUUID(), label: '选项3', value: '3' },
        ],
      },
      meta: { hasPlaceholder: true, hasOptions: true },
    },
    {
      type: 'matrix',
      name: '选择矩阵',
      icon: 'AppstoreOutlined',
      category: 'choice',
      component: () => import('@/components/form/Matrix.vue'),
      defaultConfig: {
        title: '选择矩阵',
        matrixMode: 'radio',
        matrixRows: [
          { id: generateUUID(), label: '行1' },
          { id: generateUUID(), label: '行2' },
          { id: generateUUID(), label: '行3' },
        ],
        matrixColumns: [
          { id: generateUUID(), label: '列1' },
          { id: generateUUID(), label: '列2' },
          { id: generateUUID(), label: '列3' },
        ],
      },
      meta: { hasMatrix: true },
    },
    {
      type: 'matrix-fill',
      name: '填空矩阵',
      icon: 'TableOutlined',
      category: 'choice',
      component: () => import('@/components/form/MatrixFill.vue'),
      defaultConfig: {
        title: '填空矩阵',
        matrixRows: [
          { id: generateUUID(), label: '行1' },
          { id: generateUUID(), label: '行2' },
        ],
        matrixColumns: [
          { id: generateUUID(), label: '列1' },
          { id: generateUUID(), label: '列2' },
        ],
      },
      meta: { hasMatrix: true },
    },
    {
      type: 'date',
      name: '日期',
      icon: 'CalendarOutlined',
      category: 'info',
      component: () => import('@/components/form/Date.vue'),
      defaultConfig: { title: '日期', placeholder: '请选择日期' },
    },
    {
      type: 'time-picker',
      name: '时间',
      icon: 'ClockCircleOutlined',
      category: 'info',
      component: () => import('@/components/form/TimePicker.vue'),
      defaultConfig: { title: '时间', placeholder: '请选择时间' },
    },
    {
      type: 'address',
      name: '地址',
      icon: 'EnvironmentOutlined',
      category: 'info',
      component: () => import('@/components/form/Address.vue'),
      defaultConfig: {
        title: '地址',
        props: { allowClear: true, showSearch: true, changeOnSelect: true, cascaderPlaceholder: '请选择省/市/区', detailPlaceholder: '详细地址（街道、门牌号等）' },
      },
    },
    {
      type: 'signature',
      name: '电子签名',
      icon: 'EditOutlined',
      category: 'advanced',
      component: () => import('@/components/form/Signature.vue'),
      defaultConfig: { title: '电子签名', props: { width: 400, height: 150 } },
      meta: { skipValidation: true },
    },
    {
      type: 'upload',
      name: '文件上传',
      icon: 'UploadOutlined',
      category: 'advanced',
      component: () => import('@/components/form/Upload.vue'),
      defaultConfig: { title: '文件上传', placeholder: '点击上传', props: { action: '/upload', multiple: true, maxCount: 5, maxSize: 100 } },
    },
    {
      type: 'nps',
      name: 'NPS 净推荐值',
      icon: 'ThunderboltOutlined',
      category: 'advanced',
      component: () => import('@/components/form/NpsRating.vue'),
      defaultConfig: { title: '推荐意愿', defaultValue: 0 },
      meta: { hasDescription: false },
    },
    {
      type: 'ranking',
      name: '排序题',
      icon: 'OrderedListOutlined',
      category: 'advanced',
      component: () => import('@/components/form/Ranking.vue'),
      defaultConfig: {
        title: '请按优先级排序',
        options: [
          { id: generateUUID(), label: '选项1', value: '1' },
          { id: generateUUID(), label: '选项2', value: '2' },
          { id: generateUUID(), label: '选项3', value: '3' },
          { id: generateUUID(), label: '选项4', value: '4' },
        ],
      },
      meta: { hasOptions: true },
    },
    {
      type: 'rich-text',
      name: '富文本',
      icon: 'FileTextOutlined',
      category: 'advanced',
      component: () => import('@/components/form/RichText.vue'),
      defaultConfig: { title: '富文本', defaultValue: '' },
    },
    {
      type: 'divider',
      name: '分割线',
      icon: 'MinusOutlined',
      category: 'layout',
      component: () => import('@/components/form/Divider.vue'),
      defaultConfig: { title: '' },
      meta: { isDisplay: true, skipValidation: true },
    },
    {
      type: 'page-break',
      name: '分页符',
      icon: 'PauseOutlined',
      category: 'layout',
      component: () => import('@/components/form/PageBreak.vue'),
      defaultConfig: { title: '分页符' },
      meta: { isDisplay: true, skipValidation: true },
    },
    {
      type: 'submit-button',
      name: '提交按钮',
      icon: 'SendOutlined',
      category: 'basic',
      component: () => import('@/components/form/SubmitButton.vue'),
      defaultConfig: {
        title: '提交',
        props: { btnType: 'primary', align: 'center', block: false, size: 'middle' },
      },
      meta: { isDisplay: true, skipValidation: true },
    },
  ],
}
